### ISSUE TITLE
Location service crashes the app

### ISSUE THREAD

**Issue by Milansu** [igaurab/user_location_plugin#28]
**Describe the bug**
When the location service is turned off, you get prompted with a rationale for requesting permission (Android only), the Google's location service. If you click "No Thanks" you will get prompted again the same alert until the application finally crashes. Clicking "Ok" works fine, and enables locations service.
You can see the issue in the example.

**To Reproduce**
1. Go to Settings -> Location
2. Toggle the Location off
3. Return to the app

**Expected behavior**
Clicking on "No Thanks" doesn't prompt the alert again.

**Smartphone (please complete the following information):**
 - Device: ZTE Blade A512/SM J500F
 - OS: Android
 - Version 6.0.1/5.1.1

Edit: I think it was this commit  : `35ba3dab64f5620beb671a89422f0323dee8cc96`

**Comment by igaurab** [comment]
@Milansu just looked into the issue today. Will fix in a day or two. I think there is a critical bug in the `initialize` function. Thank you for reporting the issue.

**Comment by xni06** [comment]
@Milansu Could you please see whether recent changes fix your problem? You can try it out by using this in your `pubspec.yaml`

```
  user_location:
    git:
      url: "https://github.com/igaurab/user_location_plugin.git"
      ref: "d7e1cbe2e01ad3de320b36570f7a3cf9624f7433"

```
