### ISSUE TITLE
version conflict?

### ISSUE THREAD

**Issue by paapu88** [igaurab/user_location_plugin#50]
Hello,
I get some  proj4dart related error if not using flutter_map: ^0.9.0.
But now it seems that user_location cannot use that version.

> Because user_location ^0.0.7 depends on flutter_map ^0.8.0 and user_location <0.0.7 depends on flutter_map ^0.7.0+2, user_location <0.1.0 requires flutter_map ^0.7.0+2 or ^0.8.0.
And because user_location >=0.1.0 depends on flutter_map ^0.8.2, every version of user_location requires flutter_map ^0.7.0+2 or >=0.8.0 <0.9.0.
So, because loyda_suomi depends on both flutter_map ^0.9.0 and user_location any, version solving failed.

In pubspec.yaml:  
```
flutter_map: ^0.9.0
proj4dart: any 
user_location: any
```

I did not proceed to change files gradle.properties  and build.gradle (in intructions it is not clear which one of the build.gradle)

terveisin, Markus

**Comment by xni06** [comment]
Can you try the following please in your `pubspec.yaml`? Thanks

```
  user_location:
    # path: ../user_location_plugin
    git:
      url: "https://github.com/igaurab/user_location_plugin.git"
      ref: "d7e1cbe2e01ad3de320b36570f7a3cf9624f7433"
```

**Comment by paapu88** [comment]
Thanks for a quick reply, bur with your suggested modification I get now:

> flutter run
Because every version of user_location from git depends on flutter_map ^0.8.2 and loyda_suomi depends on flutter_map ^0.9.0, user_location from git is forbidden.
So, because loyda_suomi depends on user_location from git, version solving failed.
Running "flutter pub get" in loyda_suomi...                             
pub get failed (1; So, because loyda_suomi depends on user_location from git,
version solving failed.)

( I have basically been using a copy pasted version from flutter_map to have a special-coordinate system map, so I guess I should not be the onyl one with this issue...)

**Comment by xni06** [comment]
> ( I have basically been using a copy-pasted version from flutter_map to have a special-coordinate system map, so I guess I should not be the only one with this issue...)

What's `loyda_suomi`?

JFYI, these are my dependencies that work OK at the moment:

```
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  android_intent: ^0.3.5+1
  built_collection: ^4.3.2
  built_value: ^7.0.9
  cached_network_image: ^2.0.0
  clustering_google_maps: ^0.1.2
  cupertino_icons: ^0.1.3
  data_connection_checker: ^0.3.4
  date_format: ^1.0.8
  drop_cap_text: ^1.0.7
  firebase_core: 0.4.4
  firebase_analytics: 5.0.11
  firebase_crashlytics: 0.1.3
  fluster: ^1.1.2
  flutter_appavailability:
    git:
      url: "https://github.com/pichillilorenzo/flutter_appavailability.git"
      ref: "a9e2fa38d8c9334c89d13c69c69db29030c926d5"
  flutter_bloc: ^1.0.0
  flutter_html: ^0.11.1
  flutter_map: ^0.8.2
  flutter_map_marker_cluster:
    git:
      url: "https://github.com/reaster/flutter_map_marker_cluster.git"
      ref: "9c2ca729290f7a95a36ae200e7a0a55d853078d0"
  get: ^1.11.1
  http: ^0.12.0+2
  hydrated_bloc: ^1.1.0
  image: ^2.1.4
  kiwi: ^0.2.0
  package_info: 0.4.0+13
  share: ^0.6.3+5
  shared_preferences: ^0.5.6
  sticky_headers: ^0.1.8+1
  super_tooltip: ^0.9.0
  url_launcher: ^5.4.2
  user_location:
    # path: ../user_location_plugin
    git:
      url: "https://github.com/igaurab/user_location_plugin.git"
      ref: "d7e1cbe2e01ad3de320b36570f7a3cf9624f7433"
```
